# Generated by Django 3.2.1 on 2021-05-24 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0004_alter_event_unique_together'),
        ('videos', '0002_remove_videoupload_eventkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='Eventkey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Event.event'),
            preserve_default=False,
        ),
    ]
