# Generated by Django 3.2.1 on 2021-05-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_remove_videoupload_eventkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='EventID',
            field=models.CharField(default='welcome newbie', max_length=100),
        ),
    ]
