# Generated by Django 3.2.1 on 2021-05-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0007_teacher_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherclassroom',
            name='class_url',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
