# Generated by Django 3.2.1 on 2021-05-27 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Event', '0001_initial'),
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.teacherclassroom'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('eventname', 'Room')},
        ),
    ]
