# Generated by Django 3.2.1 on 2021-05-23 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0004_studentinclassroom'),
        ('Event', '0002_event_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.teacherclassroom'),
        ),
    ]
