# Generated by Django 3.2.1 on 2021-05-23 19:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Teacher', '0005_alter_teacherclassroom_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentinclassroom',
            unique_together={('classId', 'student')},
        ),
    ]
