# Generated by Django 3.2.1 on 2021-05-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250, unique=True)),
                ('mode_active', models.BooleanField(default=False)),
                ('username', models.CharField(default='', max_length=250, unique=True)),
            ],
        ),
    ]
